export interface College {
  id: string;
  slug: string;
  name: string;
  email: string;
  phone: string;
  homepageUrl: string;
}

export const colleges: College[] = [
  {
    id: "1",
    slug: "gpc-ajmer",
    name: "Government Polytechnic College, Ajmer",
    email: "gpc.ajmer@rajasthan.gov.in",
    phone: "0145-2695195",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcajmer",
  },
  {
    id: "2",
    slug: "gpc-alwar",
    name: "Government Polytechnic College, Alwar",
    email: "gpc.alwar@rajasthan.gov.in",
    phone: "0144-2701645",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcalwar",
  },
  {
    id: "3",
    slug: "gpc-bagidora-banswara",
    name: "Government Polytechnic College Bagidora, Banswara",
    email: "gpc.banswara@rajasthan.gov.in",
    phone: "0000-0000000",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcbagidora",
  },
  {
    id: "4",
    slug: "gpc-banswara",
    name: "Government Polytechnic College, Banswara",
    email: "gpc.banswara@rajasthan.gov.in",
    phone: "0296-2254729",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcbanswara",
  },
  {
    id: "5",
    slug: "gpc-baran",
    name: "Government Polytechnic College, Baran",
    email: "gpc.baran@rajasthan.gov.in",
    phone: "0745-3297011",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcbaran",
  },
  {
    id: "6",
    slug: "gpc-barmer",
    name: "Government Polytechnic College, Barmer",
    email: "gpc.barmer@rajasthan.gov.in",
    phone: "0298-2220634",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcbarmer",
  },
  {
    id: "7",
    slug: "gpc-bikaner",
    name: "Government Polytechnic College,Bikaner",
    email: "gpc.bikaner@rajasthan.gov.in",
    phone: "0151-2542064",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcbikaner",
  },
  {
    id: "8",
    slug: "sgv-gpc-bharatpur",
    name: "Shri Gokul Verma Government Polytechnic College,Bharatpur",
    email: "gpc.bharatpur@rajasthan.gov.in",
    phone: "0564-4297002",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gwpcbharatpur",
  },
  {
    id: "9",
    slug: "gpc-bhilwara",
    name: "Government Polytechnic College Bhilwara",
    email: "gpc.bhilwara@rajasthan.gov.in",
    phone: "0148-2250111",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcbhilwara",
  },
  {
    id: "10",
    slug: "gpc-bundi",
    name: "Government Polytechnic College, Bundi",
    email: "gpc.bundi@rajasthan.gov.in",
    phone: "0747-2970021",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcbundi",
  },
  {
    id: "11",
    slug: "gpc-chittorgarh",
    name: "Government Polytechnic College Chittorgarh",
    email: "gpc.chittorgarh@rajasthan.gov.in",
    phone: "0147-2240992",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcchittorgarh",
  },
  {
    id: "12",
    slug: "gpc-churu",
    name: "Government Polytechnic College, Churu",
    email: "gpc.churu@rajasthan.gov.in",
    phone: "0156-2257794",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcchuru",
  },
  {
    id: "13",
    slug: "rpgpc-dausa",
    name: "Rajesh Pilot Government Polytechnic College,Dausa",
    email: "gpc.dausa@rajasthan.gov.in",
    phone: "0142-7204344",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcdausa",
  },
  {
    id: "14",
    slug: "rpgpc-dholpur",
    name: "Rajesh Pilot Government Polytechnic College,Dholpur",
    email: "gpc.dholpur@rajasthan.gov.in",
    phone: "0142-7204344",
    homepageUrl: "https://hte.rajasthan.gov.in/college/www.gpcdholpur.com",
  },
  {
    id: "15",
    slug: "gpc-dungarpur",
    name: "Government Polytechnic College,Dungarpur",
    email: "gpc.dungarpur@rajasthan.gov.in",
    phone: "0296-4268710",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcdungarpur",
  },
  {
    id: "16",
    slug: "gpc-hanumangarh",
    name: "Government Polytechnic College,Hanumangarh",
    email: "gpc.hanumangarh@rajasthan.gov.in",
    phone: "0155-2260044",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpchanumangarh",
  },
  {
    id: "17",
    slug: "grckpc-jaipur",
    name: "Government Ram Chandra Khaitan Polytechnic College Jaipur",
    email: "gpc.jaipur@rajasthan.gov.in",
    phone: "0141-2707829",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcjaipur",
  },
  {
    id: "18",
    slug: "gpc-jalore-pali",
    name: "Government Polytechnic College, Jalore (Camp Pali)",
    email: "gpc.jalore@rajasthan.gov.in",
    phone: "0293-2263505",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcjalore",
  },
  {
    id: "19",
    slug: "gpc-jaisalmer",
    name: "Government Polytechnic College, Jaisalmer",
    email: "gpc.jaisalmerh@rajasthan.gov.in",
    phone: "0823-3329769",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcjaisalmer",
  },
  {
    id: "20",
    slug: "gpc-jhalawar",
    name: "Government Polytechnic College, Jhalawar",
    email: "gpc.jhalawar@rajasthan.gov.in",
    phone: "0743-2233282",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcjhalawar",
  },
  {
    id: "21",
    slug: "gpc-jodhpur",
    name: "Government Polytechnic College, Jodhpur",
    email: "gpc.jodhpur@rajasthan.gov.in",
    phone: "0291-2649439",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcjodhpur",
  },
  {
    id: "22",
    slug: "gpc-jhunjhunu",
    name: "Government Polytechnic College, Jhunjhunu",
    email: "gpcjhunjhunu.@rajasthan.gov.in",
    phone: "0159-2297007",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcjhunjhunu",
  },
  {
    id: "23",
    slug: "gpc-karauli-alwar",
    name: "Government Polytechnic College, Karauli (Camp- Alwar)",
    email: "gpc.karauli@rajasthan.gov.in",
    phone: "0144-2701645",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpckaroli",
  },
  {
    id: "24",
    slug: "gpc-kota",
    name: "Government Polytechnic College, Kota",
    email: "gpc.kota@rajasthan.gov.in",
    phone: "0744-2365538",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpckota",
  },
  {
    id: "25",
    slug: "gpc-kelwara",
    name: "Government Polytechnic College, Kelwara",
    email: "gpc.kelwara@rajasthan.gov.in",
    phone: "0744-2365538",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpckelwara",
  },
  {
    id: "26",
    slug: "gpc-mandore",
    name: "Government Polytechnic College, Mandore",
    email: "gpc.mandore@rajasthan.gov.in",
    phone: "0158-2247505",
    homepageUrl: "https://hte.rajasthan.gov.in/college/gpcmandore",
  },
  {
    id: "27",
    slug: "gpc-nagaur",
    name: "Government Polytechnic College, Nagaur",
    email: "gpc.nagaur@rajasthan.gov.in",
    phone: "0158-2247505",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcnagaur",
  },
  {
    id: "28",
    slug: "gpc-neemrana",
    name: "Government Polytechnic College Neemrana (Alwar)-Rajasthan",
    email: "gpc.neemrana@rajasthan.gov.in",
    phone: "0149-4297822",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcneemrana",
  },
  {
    id: "29",
    slug: "gpc-pali",
    name: "Government Polytechnic College Pali",
    email: "gpc.pali@rajasthan.gov.in",
    phone: "0293-2263505",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcpali",
  },
  {
    id: "30",
    slug: "gpc-pratapgarh",
    name: "Government Polytechnic College Pratapgarh",
    email: "gpc.pratapgarh@rajasthan.gov.in",
    phone: "0969-4150550",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcpratapgarp",
  },
  {
    id: "31",
    slug: "gpc-rajsamand",
    name: "Government Polytechnic College, Rajsamand",
    email: "gpc.rajsamand@rajasthan.gov.in",
    phone: "0295-2221197",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcrajsamand",
  },
  {
    id: "32",
    slug: "gpc-sawai-madhopur",
    name: "Government Polytechnic College,Sawai Madhopur",
    email: "gpc.smadhopur@rajasthan.gov.in",
    phone: "0746-2220891",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcsawaimadhopur",
  },
  {
    id: "33",
    slug: "gpc-sikar",
    name: "Govt. Polytechnic College,Sikar",
    email: "gpc.sikar@rajasthan.gov.in",
    phone: "0157-2274020",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcsikar",
  },
  {
    id: "34",
    slug: "sgbb-gpc-sirohi",
    name: "SGBB Government Polytechnic College Sirohi (Raj.)",
    email: "gpc.sirohi@rajasthan.gov.inv.In",
    phone: "0297-2222401",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcsirohi",
  },
  {
    id: "35",
    slug: "cmrb-gpc-sriganganagar",
    name: "CMRB Government Polytechnic College , Sriganganagar",
    email: "gpc.sriganganagar@rajasthan.gov.in",
    phone: "0154-2482700",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcsriganganagar",
  },
  {
    id: "36",
    slug: "gpc-tonk",
    name: "Government Polytechnic College, Tonk",
    email: "gpc.tonk@rajasthan.gov.in",
    phone: "01432-260888",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpctonk",
  },
  {
    id: "37",
    slug: "gpc-udaipur",
    name: "Government Polytechnic College, Udaipur",
    email: "gpc.udaipur@rajasthan.gov.in",
    phone: "0294-2491575",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcudaipur",
  },
  {
    id: "38",
    slug: "gwpc-ajmer",
    name: "Goverment Women Polytechnic College,Ajmer",
    email: "gwpc.ajmer@rajasthan.gov.in",
    phone: "0145-2695231",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gwpcajmer",
  },
  {
    id: "39",
    slug: "gwpc-bikaner",
    name: "Goverment Women Polytechnic College, Bikaner",
    email: "gwpc.bikaner@rajasthan.gov.in",
    phone: "0151-2528874",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gwpcbikaner",
  },
  {
    id: "40",
    slug: "gwpc-bharatpur",
    name: "Government Women Polytechnic College Bharatpur",
    email: "gwpc.bharatpur@rajasthan.gov.in",
    phone: "0564-4297015",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gpcbharatpur",
  },
  {
    id: "41",
    slug: "gwpc-jaipur",
    name: "Government Women Polytechnic College.Jaipur",
    email: "gwpc.jaipur@rajasthan.gov.in",
    phone: "0141-2706688",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gwpcjaipur",
  },
  {
    id: "42",
    slug: "grwpc-jodhpur",
    name: "Government Residential Women Polytechnic College, Jodhpur",
    email: "principal.gwpc.jdh@rajasthan.gov.in",
    phone: "0291-2434187",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gwpcjodhpur",
  },
  {
    id: "43",
    slug: "gwpc-kota",
    name: "Government Women Polytechnic College, Kota",
    email: "gwpc.kota@rajasthan.gov.in",
    phone: "0744-2420313",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gwpckota",
  },
  {
    id: "44",
    slug: "gwpc-sanganer",
    name: "Government Women Polytechnic College, Sanganer",
    email: "gwpc.sanganer@rajasthan.gov.in",
    phone: "0141-2706688",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gwpcsanganer",
  },
  {
    id: "45",
    slug: "gwpc-udaipur",
    name: "Government Women Polytechnic College,Udaipur",
    email: "gwpc.udaipur@rajasthan.gov.in",
    phone: "0294-2491575",
    homepageUrl: "http://hte.rajasthan.gov.in/college/gwpcudaipur",
  },
  {
    id: "46",
    slug: "ttc-lrdc-jodhpur",
    name: "(TTC,LRDC(Jodhpur))",
    email: "ttc.jodhpur@rajasthan.gov.in",
    phone: "0291-2431072",
    homepageUrl: "http://hte.rajasthan.gov.in/college/ttcjodhpur",
  },
];
