-- ============================================
-- SCHEMA FOR DOCUMENT STORAGE & RAG SYSTEM
-- Uses UUIDs for all primary keys
-- ============================================

-- Create the storage bucket for documents if it doesn't exist
insert into storage.buckets (id, name, public)
values ('documents', 'documents', true)
on conflict (id) do nothing;

-- Set up RLS policies for the storage bucket (Optional: adjust as needed)
-- Allow public read access (or restrict to authenticated users)
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'documents' );

-- Allow authenticated users to upload
create policy "Authenticated Upload"
on storage.objects for insert
with check ( bucket_id = 'documents' and auth.role() = 'authenticated' );

-- Enable required extensions
create extension if not exists vector;
create extension if not exists "uuid-ossp"; -- For uuid_generate_v4()

-- ============================================
-- FILES TABLE - Stores uploaded file metadata
-- ============================================
create table if not exists files (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  url text not null, -- Storage path
  college_id text not null,
  size bigint,
  type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  -- RAG Enhancement: Document type for differentiating info docs vs structured docs (forms/notices)
  document_type text default 'info' check (document_type in ('info', 'structured', 'text', 'website')),
  -- RAG Enhancement: Public URL for clickable citations
  source_url text
);

-- Index for faster college lookups
create index if not exists files_college_id_idx on files(college_id);

-- ============================================
-- DOCUMENTS TABLE - Stores text chunks with embeddings
-- ============================================
create table if not exists documents (
  id uuid primary key default uuid_generate_v4(),
  content text not null, -- The text chunk
  metadata jsonb, -- { filename: "policy.pdf", college_id: "...", chunk_index: 0 }
  embedding vector(1536), -- OpenAI embedding (1536 dimensions)
  file_id uuid references files(id) on delete cascade, -- Link to parent file
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for foreign key lookups
create index if not exists documents_file_id_idx on documents(file_id);

-- ============================================
-- VECTOR SEARCH FUNCTION
-- ============================================
-- Uses text parameter for embedding to avoid type casting issues
-- Includes filter parameter for college_id filtering
create or replace function match_documents (
  query_embedding_text text,
  match_threshold float,
  match_count int,
  filter jsonb default '{}'::jsonb
)
returns table (
  id uuid,
  content text,
  metadata jsonb,
  similarity float
)
language sql
as $$
  select
    documents.id,
    documents.content,
    documents.metadata,
    1 - (documents.embedding <=> query_embedding_text::vector(1536)) as similarity
  from documents
  where 1 - (documents.embedding <=> query_embedding_text::vector(1536)) >= match_threshold
  and documents.metadata @> filter
  limit match_count;
$$;

-- ============================================
-- VECTOR INDEX FOR FAST SIMILARITY SEARCH
-- ============================================
-- Note: You might need to have some data in the table before creating this index effectively, 
-- or use HNSW if supported by your Supabase tier.
create index if not exists documents_embedding_idx 
on documents using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

-- ============================================
-- USERS TABLE - Email-based auth (no password)
-- ============================================
create table if not exists users (
  id uuid primary key default uuid_generate_v4(),
  email text not null,
  college_id text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_active_at timestamp with time zone default timezone('utc'::text, now()) not null,
  -- Unique constraint on email + college_id combination
  constraint users_email_college_unique unique (email, college_id)
);

-- Indexes for faster lookups
create index if not exists users_email_idx on users(email);
create index if not exists users_college_id_idx on users(college_id);

-- ============================================
-- CONVERSATIONS TABLE - Uses session_id as primary key
-- session_id is a UUID generated by the widget and used for both text and voice
-- ============================================
create table if not exists conversations (
  id text primary key, -- This IS the session_id from the widget
  user_id uuid not null references users(id) on delete cascade,
  college_id text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for faster lookups
create index if not exists conversations_user_id_idx on conversations(user_id);
create index if not exists conversations_college_id_idx on conversations(college_id);

-- ============================================
-- MESSAGES TABLE - Stores encrypted chat messages
-- ============================================
create table if not exists messages (
  id uuid primary key default uuid_generate_v4(),
  conversation_id uuid not null references conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content_encrypted text not null,
  content_iv text not null,
  content_tag text not null,
  is_voice boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for faster lookups
create index if not exists messages_conversation_id_idx on messages(conversation_id);
create index if not exists messages_created_at_idx on messages(created_at);

-- ============================================
-- KNOWLEDGE GAPS TABLE - Stores unanswered user queries
-- ============================================
-- Enable pg_net extension for async HTTP (required for webhooks)
create extension if not exists pg_net with schema extensions;

create table if not exists knowledge_gaps (
  id uuid primary key default uuid_generate_v4(),
  query text not null,
  ai_comment text not null,
  college_id text not null,
  user_email text,
  answer text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  answered_at timestamp with time zone,
  cascaded_at timestamp with time zone
);

-- Indexes
create index if not exists knowledge_gaps_college_id_idx on knowledge_gaps(college_id);
create index if not exists knowledge_gaps_pending_idx on knowledge_gaps(id) where answer is null;

-- Comments
comment on table knowledge_gaps is 'Stores user queries that AI could not answer from the knowledge base';
comment on column knowledge_gaps.query is 'Original user question';
comment on column knowledge_gaps.ai_comment is 'AI explanation of what info is missing';
comment on column knowledge_gaps.answer is 'Admin-provided answer (null until answered)';
comment on column knowledge_gaps.cascaded_at is 'Timestamp when Q&A was added to RAG';

-- Function to call edge function on knowledge gap answer
create or replace function handle_knowledge_gap_answer()
returns trigger
language plpgsql
security definer
as $$
begin
  -- Only trigger if answer changed from null to a value
  if old.answer is null and new.answer is not null and new.cascaded_at is null then
    perform net.http_post(
      url := 'https://trkrrxdlipgcydxroqve.supabase.co/functions/v1/cascade-knowledge-gap',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || current_setting('app.settings.service_role_key', true)
      ),
      body := jsonb_build_object(
        'type', 'UPDATE',
        'table', 'knowledge_gaps',
        'schema', 'public',
        'record', to_jsonb(new.*),
        'old_record', to_jsonb(old.*)
      )
    );
  end if;
  return new;
end;
$$;

-- Trigger for knowledge_gaps updates
create trigger on_knowledge_gap_answer
  after update on knowledge_gaps
  for each row
  execute function handle_knowledge_gap_answer();

-- ============================================
-- MIGRATION HELPER (Run if you have existing data)
-- ============================================
-- If you need to migrate from bigserial to UUID, run this migration:
-- 
-- Step 1: Add new UUID columns
-- ALTER TABLE files ADD COLUMN new_id uuid DEFAULT uuid_generate_v4();
-- ALTER TABLE documents ADD COLUMN new_id uuid DEFAULT uuid_generate_v4();
-- ALTER TABLE documents ADD COLUMN new_file_id uuid;
-- 
-- Step 2: Create mapping and update references
-- UPDATE documents d SET new_file_id = f.new_id FROM files f WHERE d.file_id = f.id;
-- 
-- Step 3: Drop old columns and rename new ones
-- ALTER TABLE documents DROP CONSTRAINT documents_file_id_fkey;
-- ALTER TABLE documents DROP COLUMN file_id;
-- ALTER TABLE documents RENAME COLUMN new_file_id TO file_id;
-- ALTER TABLE files DROP COLUMN id;
-- ALTER TABLE files RENAME COLUMN new_id TO id;
-- ALTER TABLE files ADD PRIMARY KEY (id);
-- ALTER TABLE documents DROP COLUMN id;
-- ALTER TABLE documents RENAME COLUMN new_id TO id;
-- ALTER TABLE documents ADD PRIMARY KEY (id);
-- ALTER TABLE documents ADD FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE;
